---
- name: Downloading and enable the EPEL repository definitions.
  yum: name=http://repos.mesosphere.io/el/7/noarch/RPMS/mesosphere-el-repo-7-1.noarch.rpm state=present

- group: name={{ zookeeper_group }} system=yes
- user: name={{ zookeeper_user }} group={{ zookeeper_group }} system=yes

- name: Create zookeeper logs folder.
  file: path={{log_dir}} state=directory recurse=yes owner={{ zookeeper_user }} group={{ zookeeper_group }}
  tags: bootstrap

- name: Change ownership on zookeeper directory.
  file: path={{zookeeper_dir}} state=directory owner={{ zookeeper_user }} group={{ zookeeper_group }} recurse=yes
  tags: bootstrap

- name: Create zookeeper data folder.
  file: path={{data_dir}} state=directory recurse=yes owner={{ zookeeper_user }} group={{ zookeeper_group }}
  tags: bootstrap

- name: Create zookeeper logs folder.
  file: path={{log_dir}} state=directory recurse=yes owner={{ zookeeper_user }} group={{ zookeeper_group }}
  tags: bootstrap

- name: Install Zookeeper Packages
  yum: pkg={{ item }} state=present
  with_items:
    - mesosphere-zookeeper
    - libselinux-python

- name: Write myid file.
  template: src=myid.j2 dest={{ data_dir }}/myid owner={{ zookeeper_user }} group={{ zookeeper_group }}
  tags: deploy

- name: Configure zookeeper
  template: src=zoo.cfg.j2 dest={{ zookeeper_dir }}/conf/zoo.cfg owner={{ zookeeper_user }} group={{ zookeeper_group }}
  tags: deploy

- name: Configure zookeeper
  template: src=zookeeper.conf.sysd.j2 dest=/usr/lib/systemd/system/zookeeper.service
  tags: deploy

- name: Start zookeeper
  service: name=zookeeper state=restarted 
  tags: deploy
