---
- name: Downloading and enable the EPEL repository definitions.
  yum: name=http://repos.mesosphere.io/el/7/noarch/RPMS/mesosphere-el-repo-7-1.noarch.rpm state=present

- name: create zookeeper log directory
  file: path={{ log_dir }} state=directory

- name: Install Zookeeper Packages
  yum: pkg={{ item }} state=present
  with_items:
    - mesosphere-zookeeper
    - libselinux-python

- name: Write myid file.
  template: src=myid.j2 dest={{ data_dir }}/myid
  tags: deploy

- name: Configure zookeeper
  template: src=zoo.cfg.j2 dest={{ zookeeper_dir }}/conf/zoo.cfg
  tags: deploy

- name: Start zookeeper
  service: name=zookeeper state=restarted 
  tags: deploy
