---
- name: Downloading and enable the EPEL repository definitions.
  yum: name=http://repos.mesosphere.io/el/7/noarch/RPMS/mesosphere-el-repo-7-1.noarch.rpm state=present

- name: Install Zookeeper Packages
  yum: pkg={{ item }} state=present
  with_items:
    - mesosphere-zookeeper
    - libselinux-python

- file: path=/opt/src state=directory
- file: path={{zookeeper_dir}} state=directory

- group: name=zookeeper system=yes
- user: name=zookeeper group=zookeeper system=yes

- name: Change ownership on zookeeper directory.
  file: path={{zookeeper_dir}} state=directory owner=zookeeper group=zookeeper recurse=yes
  tags: bootstrap

- name: Create zookeeper data folder.
  file: path={{data_dir}} state=directory recurse=yes owner=zookeeper group=zookeeper
  tags: bootstrap

- name: Create zookeeper logs folder.
  file: path={{log_dir}} state=directory recurse=yes owner=zookeeper group=zookeeper
  tags: bootstrap

- name: Write myid file.
  template: src=myid.j2 dest={{data_dir}}/myid owner=zookeeper group=zookeeper
  tags: deploy

- name: Configure zookeeper
  template: src=zoo.cfg.j2 dest={{ zookeeper_dir }}/conf/zoo.cfg owner=zookeeper group=zookeeper
  tags: deploy

- name: Start zookeeper
  service: name=zookeeper state=restarted 
  tags: deploy
